import { useState, useEffect } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '../ui/card';
import { Button } from '../ui/button';
import { Input } from '../ui/input';
import { Label } from '../ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '../ui/select';
import { Badge } from '../ui/badge';
import { 
  Download, 
  FileSpreadsheet, 
  User,
  Search,
  FileText,
  Users
} from 'lucide-react';
import { toast } from 'sonner@2.0.3';
import { projectId, publicAnonKey } from '../../utils/supabase/info';

interface ClientReportsProps {
  currentUser: any;
  canAccessClinical: boolean;
  canAccessMentalHealth: boolean;
  canExport: boolean;
}

export function ClientReports({ currentUser, canAccessClinical, canAccessMentalHealth, canExport }: ClientReportsProps) {
  const [reportType, setReportType] = useState<'individual' | 'summary'>('individual');
  const [clients, setClients] = useState<any[]>([]);
  const [selectedClient, setSelectedClient] = useState('');
  const [searchTerm, setSearchTerm] = useState('');
  const [loading, setLoading] = useState(false);
  const [clientReport, setClientReport] = useState<any>(null);

  useEffect(() => {
    loadClients();
  }, []);

  const loadClients = async () => {
    try {
      const response = await fetch(
        `https://${projectId}.supabase.co/functions/v1/make-server-56fd5521/clients`,
        { headers: { 'Authorization': `Bearer ${publicAnonKey}` } }
      );
      const data = await response.json();
      if (data.success) {
        setClients(data.clients || []);
      }
    } catch (error) {
      console.error('Error loading clients:', error);
    }
  };

  const loadClientReport = async () => {
    if (!selectedClient) {
      toast.error('Please select a client');
      return;
    }

    setLoading(true);
    try {
      const response = await fetch(
        `https://${projectId}.supabase.co/functions/v1/make-server-56fd5521/reports/client/${selectedClient}`,
        { headers: { 'Authorization': `Bearer ${publicAnonKey}` } }
      );

      const data = await response.json();
      if (data.success) {
        setClientReport(data.report);
      } else {
        toast.error('Failed to load client report');
      }
    } catch (error) {
      console.error('Error loading client report:', error);
      toast.error('Failed to load client report');
    } finally {
      setLoading(false);
    }
  };

  const handleExportIndividualPDF = () => {
    if (!canExport) {
      toast.error('You do not have export permissions');
      return;
    }
    
    if (!clientReport) {
      toast.error('No client report to export');
      return;
    }

    try {
      const client = clientReport.client;
      const pdfContent = `
        <!DOCTYPE html>
        <html>
        <head>
          <style>
            body { font-family: Arial, sans-serif; padding: 40px; }
            h1 { color: #4f46e5; border-bottom: 2px solid #4f46e5; padding-bottom: 10px; }
            h2 { color: #333; margin-top: 30px; border-bottom: 1px solid #ddd; padding-bottom: 5px; }
            table { width: 100%; border-collapse: collapse; margin-top: 20px; }
            th, td { border: 1px solid #ddd; padding: 12px; text-align: left; }
            th { background-color: #4f46e5; color: white; }
            .info-grid { display: grid; grid-template-columns: repeat(2, 1fr); gap: 20px; margin: 20px 0; }
            .info-item { padding: 10px; border-left: 3px solid #4f46e5; background: #f9fafb; }
            .info-label { color: #666; font-size: 12px; margin-bottom: 4px; }
            .info-value { font-weight: bold; color: #333; }
            .badge { display: inline-block; padding: 4px 12px; border-radius: 12px; font-size: 12px; margin: 2px; }
            .badge-success { background: #d1fae5; color: #065f46; }
            .badge-warning { background: #fef3c7; color: #92400e; }
            .badge-danger { background: #fee2e2; color: #991b1b; }
            .logo { font-size: 24px; font-weight: bold; color: #4f46e5; margin-bottom: 10px; }
          </style>
        </head>
        <body>
          <div class="logo">MEWA M&E System</div>
          <h1>Individual Client Report</h1>
          <p><strong>Generated:</strong> ${new Date().toLocaleString()}</p>
          <p><strong>Generated by:</strong> ${currentUser.name} (${currentUser.role})</p>
          
          <h2>Demographic Information</h2>
          <div class="info-grid">
            <div class="info-item">
              <div class="info-label">Client ID</div>
              <div class="info-value">${client.clientId}</div>
            </div>
            <div class="info-item">
              <div class="info-label">Full Name</div>
              <div class="info-value">${client.name}</div>
            </div>
            <div class="info-item">
              <div class="info-label">Age</div>
              <div class="info-value">${client.age} years</div>
            </div>
            <div class="info-item">
              <div class="info-label">Gender</div>
              <div class="info-value">${client.gender}</div>
            </div>
            <div class="info-item">
              <div class="info-label">Location</div>
              <div class="info-value">${client.location}</div>
            </div>
            <div class="info-item">
              <div class="info-label">Registration Date</div>
              <div class="info-value">${new Date(client.registrationDate || client.createdAt).toLocaleDateString()}</div>
            </div>
          </div>

          ${clientReport.programs && clientReport.programs.length > 0 ? `
            <h2>Program Enrollment</h2>
            <p>${clientReport.programs.map((p: string) => `<span class="badge badge-success">${p}</span>`).join(' ')}</p>
          ` : ''}

          <h2>Visit Summary</h2>
          <div class="info-grid">
            <div class="info-item">
              <div class="info-label">Total Visits</div>
              <div class="info-value">${clientReport.visitCount || 0}</div>
            </div>
            <div class="info-item">
              <div class="info-label">Last Visit</div>
              <div class="info-value">${clientReport.lastVisit ? new Date(clientReport.lastVisit).toLocaleDateString() : 'N/A'}</div>
            </div>
            <div class="info-item">
              <div class="info-label">Total Services</div>
              <div class="info-value">${clientReport.serviceCount || 0}</div>
            </div>
            <div class="info-item">
              <div class="info-label">Status</div>
              <div class="info-value">${client.status || 'Active'}</div>
            </div>
          </div>

          ${clientReport.services ? `
            <h2>Services Breakdown</h2>
            <table>
              <tr><th>Service Type</th><th>Count</th></tr>
              ${Object.entries(clientReport.services).map(([service, count]) => `
                <tr><td>${service}</td><td>${count}</td></tr>
              `).join('')}
            </table>
          ` : ''}

          ${clientReport.riskFlags && clientReport.riskFlags.length > 0 ? `
            <h2>Risk Flags</h2>
            <p>${clientReport.riskFlags.map((flag: string) => `<span class="badge badge-danger">${flag}</span>`).join(' ')}</p>
          ` : ''}

          ${canAccessMentalHealth && clientReport.mentalHealthTrend ? `
            <h2>Mental Health Screening</h2>
            <div class="info-grid">
              <div class="info-item">
                <div class="info-label">Latest PHQ-9 Score</div>
                <div class="info-value">${clientReport.mentalHealthTrend.latestPHQ9 || 'N/A'}</div>
              </div>
              <div class="info-item">
                <div class="info-label">Latest GAD-7 Score</div>
                <div class="info-value">${clientReport.mentalHealthTrend.latestGAD7 || 'N/A'}</div>
              </div>
            </div>
          ` : ''}

          <p style="margin-top: 60px; color: #666; font-size: 12px; border-top: 1px solid #ddd; padding-top: 20px;">
            This is a confidential client report generated by MEWA M&E System.<br>
            Generated on ${new Date().toLocaleString()} by ${currentUser.name}.<br>
            This document contains sensitive health information and should be handled according to MEWA's privacy policies.
          </p>
        </body>
        </html>
      `;

      const blob = new Blob([pdfContent], { type: 'text/html' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `client_${client.clientId}_report_${new Date().toISOString().split('T')[0]}.html`;
      a.click();
      URL.revokeObjectURL(url);
      
      toast.success('Client report exported! Open the HTML file and use your browser to print as PDF.');
    } catch (error) {
      console.error('Error exporting PDF:', error);
      toast.error('Failed to export report');
    }
  };

  const handleExportSummaryExcel = () => {
    if (!canExport) {
      toast.error('You do not have export permissions');
      return;
    }

    try {
      let csvContent = 'Client Summary Report\n';
      csvContent += `Generated,${new Date().toLocaleString()}\n`;
      csvContent += `Generated by,${currentUser.name} (${currentUser.role})\n\n`;
      
      csvContent += 'Client ID,Name,Age,Gender,Location,Programs,Status,Last Visit,Total Visits\n';
      
      filteredClients.forEach((client: any) => {
        csvContent += `${client.clientId || ''},`;
        csvContent += `${client.name || ''},`;
        csvContent += `${client.age || ''},`;
        csvContent += `${client.gender || ''},`;
        csvContent += `${client.location || ''},`;
        csvContent += `${client.programs?.length || 0},`;
        csvContent += `${client.status || 'Active'},`;
        csvContent += `${client.lastVisit ? new Date(client.lastVisit).toLocaleDateString() : 'N/A'},`;
        csvContent += `${client.visitCount || 0}\n`;
      });

      const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `client_summary_${new Date().toISOString().split('T')[0]}.csv`;
      a.click();
      URL.revokeObjectURL(url);
      
      toast.success('Client summary exported to Excel/CSV!');
    } catch (error) {
      console.error('Error exporting Excel:', error);
      toast.error('Failed to export report');
    }
  };

  const filteredClients = clients.filter(client => 
    client.name?.toLowerCase().includes(searchTerm.toLowerCase()) ||
    client.clientId?.toLowerCase().includes(searchTerm.toLowerCase())
  );

  return (
    <div className="space-y-6">
      {/* Report Type Selection */}
      <Card>
        <CardHeader>
          <CardTitle>Client Report Type</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-2 gap-4">
            <Button
              variant={reportType === 'individual' ? 'default' : 'outline'}
              onClick={() => setReportType('individual')}
              className="h-24 flex-col"
            >
              <User className="w-8 h-8 mb-2" />
              <div>
                <p className="font-semibold">Individual Client Report</p>
                <p className="text-xs opacity-75">Comprehensive client history PDF</p>
              </div>
            </Button>

            <Button
              variant={reportType === 'summary' ? 'default' : 'outline'}
              onClick={() => setReportType('summary')}
              className="h-24 flex-col"
            >
              <Users className="w-8 h-8 mb-2" />
              <div>
                <p className="font-semibold">Client Summary Table</p>
                <p className="text-xs opacity-75">Excel export of all clients</p>
              </div>
            </Button>
          </div>
        </CardContent>
      </Card>

      {/* Individual Client Report */}
      {reportType === 'individual' && (
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <User className="w-5 h-5" />
              Individual Client Report
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            {/* Client Selection */}
            <div>
              <Label>Search and Select Client</Label>
              <div className="flex gap-2">
                <div className="flex-1">
                  <Input
                    placeholder="Search by name or ID..."
                    value={searchTerm}
                    onChange={(e) => setSearchTerm(e.target.value)}
                    className="mb-2"
                  />
                  <Select value={selectedClient} onValueChange={setSelectedClient}>
                    <SelectTrigger>
                      <SelectValue placeholder="Select a client" />
                    </SelectTrigger>
                    <SelectContent>
                      {filteredClients.map(client => (
                        <SelectItem key={client.id} value={client.id}>
                          {client.clientId} - {client.name}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
                <Button onClick={loadClientReport} disabled={loading || !selectedClient}>
                  <Search className="w-4 h-4 mr-2" />
                  {loading ? 'Loading...' : 'Load Report'}
                </Button>
              </div>
            </div>

            {/* Client Report Preview */}
            {clientReport && (
              <div className="border rounded-lg p-6 space-y-6 bg-white">
                {/* Header */}
                <div className="border-b pb-4">
                  <div className="flex items-start justify-between mb-4">
                    <div>
                      <h2 className="text-2xl font-semibold mb-2">Client Report</h2>
                      <p className="text-gray-600">Generated on {new Date().toLocaleDateString()}</p>
                    </div>
                    <Badge>{clientReport.client.status}</Badge>
                  </div>
                </div>

                {/* Demographics */}
                <div>
                  <h3 className="font-semibold mb-3">Demographic Information</h3>
                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <p className="text-sm text-gray-500">Client ID</p>
                      <p className="font-medium">{clientReport.client.clientId}</p>
                    </div>
                    <div>
                      <p className="text-sm text-gray-500">Name</p>
                      <p className="font-medium">{clientReport.client.name}</p>
                    </div>
                    <div>
                      <p className="text-sm text-gray-500">Age</p>
                      <p className="font-medium">{clientReport.client.age} years</p>
                    </div>
                    <div>
                      <p className="text-sm text-gray-500">Gender</p>
                      <p className="font-medium">{clientReport.client.gender}</p>
                    </div>
                    <div>
                      <p className="text-sm text-gray-500">Location</p>
                      <p className="font-medium">{clientReport.client.location}</p>
                    </div>
                    <div>
                      <p className="text-sm text-gray-500">Registration Date</p>
                      <p className="font-medium">{new Date(clientReport.client.registrationDate).toLocaleDateString()}</p>
                    </div>
                  </div>
                </div>

                {/* Program Enrollment */}
                {clientReport.programs && clientReport.programs.length > 0 && (
                  <div>
                    <h3 className="font-semibold mb-3">Program Enrollment</h3>
                    <div className="flex flex-wrap gap-2">
                      {clientReport.programs.map((program: string, idx: number) => (
                        <Badge key={idx} variant="outline">{program}</Badge>
                      ))}
                    </div>
                  </div>
                )}

                {/* Visit Summary */}
                <div>
                  <h3 className="font-semibold mb-3">Visit Summary</h3>
                  <div className="grid grid-cols-3 gap-4">
                    <div className="p-4 border rounded-lg">
                      <p className="text-sm text-gray-500">Total Visits</p>
                      <p className="text-2xl font-semibold">{clientReport.visitCount || 0}</p>
                    </div>
                    <div className="p-4 border rounded-lg">
                      <p className="text-sm text-gray-500">Last Visit</p>
                      <p className="text-sm font-medium">
                        {clientReport.lastVisit ? new Date(clientReport.lastVisit).toLocaleDateString() : 'N/A'}
                      </p>
                    </div>
                    <div className="p-4 border rounded-lg">
                      <p className="text-sm text-gray-500">Total Services</p>
                      <p className="text-2xl font-semibold">{clientReport.serviceCount || 0}</p>
                    </div>
                  </div>
                </div>

                {/* Services Breakdown */}
                {clientReport.services && (
                  <div>
                    <h3 className="font-semibold mb-3">Services Received</h3>
                    <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
                      {Object.entries(clientReport.services).map(([service, count]: [string, any]) => (
                        <div key={service} className="p-3 border rounded-lg">
                          <p className="text-xs text-gray-500">{service}</p>
                          <p className="text-lg font-semibold">{count}</p>
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                {/* Risk Flags */}
                {clientReport.riskFlags && clientReport.riskFlags.length > 0 && (
                  <div>
                    <h3 className="font-semibold mb-3 text-red-600">Risk Flags</h3>
                    <div className="flex flex-wrap gap-2">
                      {clientReport.riskFlags.map((flag: string, idx: number) => (
                        <Badge key={idx} className="bg-red-100 text-red-800">{flag}</Badge>
                      ))}
                    </div>
                  </div>
                )}

                {/* Mental Health Trends (if accessible) */}
                {canAccessMentalHealth && clientReport.mentalHealthTrend && (
                  <div>
                    <h3 className="font-semibold mb-3">Mental Health Screening Trends</h3>
                    <div className="grid grid-cols-2 gap-4">
                      <div className="p-4 border rounded-lg">
                        <p className="text-sm text-gray-500 mb-2">Latest PHQ-9 Score</p>
                        <p className="text-2xl font-semibold">{clientReport.mentalHealthTrend.latestPHQ9 || 'N/A'}</p>
                      </div>
                      <div className="p-4 border rounded-lg">
                        <p className="text-sm text-gray-500 mb-2">Latest GAD-7 Score</p>
                        <p className="text-2xl font-semibold">{clientReport.mentalHealthTrend.latestGAD7 || 'N/A'}</p>
                      </div>
                    </div>
                  </div>
                )}

                {/* Export Button */}
                {canExport && (
                  <div className="pt-4 border-t">
                    <Button onClick={handleExportIndividualPDF}>
                      <FileText className="w-4 h-4 mr-2" />
                      Export as PDF
                    </Button>
                  </div>
                )}
              </div>
            )}

            {!clientReport && !loading && (
              <div className="py-12 text-center text-gray-500 border rounded-lg">
                <User className="w-12 h-12 mx-auto mb-4 text-gray-300" />
                <p>Select a client and click "Load Report" to view their comprehensive report</p>
              </div>
            )}
          </CardContent>
        </Card>
      )}

      {/* Client Summary Table */}
      {reportType === 'summary' && (
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <Users className="w-5 h-5" />
                Client Summary Table
              </div>
              {canExport && (
                <Button onClick={handleExportSummaryExcel}>
                  <FileSpreadsheet className="w-4 h-4 mr-2" />
                  Export to Excel
                </Button>
              )}
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              {/* Search */}
              <Input
                placeholder="Search clients..."
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
              />

              {/* Table */}
              <div className="border rounded-lg overflow-hidden">
                <div className="overflow-x-auto">
                  <table className="w-full">
                    <thead className="bg-gray-50">
                      <tr>
                        <th className="px-4 py-3 text-left text-xs">Client ID</th>
                        <th className="px-4 py-3 text-left text-xs">Name</th>
                        <th className="px-4 py-3 text-left text-xs">Age</th>
                        <th className="px-4 py-3 text-left text-xs">Gender</th>
                        <th className="px-4 py-3 text-left text-xs">Location</th>
                        <th className="px-4 py-3 text-left text-xs">Programs</th>
                        <th className="px-4 py-3 text-left text-xs">Status</th>
                        <th className="px-4 py-3 text-left text-xs">Last Visit</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y">
                      {filteredClients.map((client) => (
                        <tr key={client.id} className="hover:bg-gray-50">
                          <td className="px-4 py-3 text-sm">{client.clientId}</td>
                          <td className="px-4 py-3 text-sm">{client.name}</td>
                          <td className="px-4 py-3 text-sm">{client.age}</td>
                          <td className="px-4 py-3 text-sm">{client.gender}</td>
                          <td className="px-4 py-3 text-sm">{client.location}</td>
                          <td className="px-4 py-3 text-sm">
                            {client.programs?.length || 0} programs
                          </td>
                          <td className="px-4 py-3 text-sm">
                            <Badge variant="outline">{client.status}</Badge>
                          </td>
                          <td className="px-4 py-3 text-sm">
                            {client.lastVisit ? new Date(client.lastVisit).toLocaleDateString() : 'N/A'}
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>

              <p className="text-xs text-gray-500">
                Showing {filteredClients.length} of {clients.length} clients
              </p>
            </div>
          </CardContent>
        </Card>
      )}
    </div>
  );
}