import { useState, useEffect } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '../ui/card';
import { Button } from '../ui/button';
import { Input } from '../ui/input';
import { Label } from '../ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '../ui/select';
import { Badge } from '../ui/badge';
import { 
  Download, 
  FileSpreadsheet, 
  Package,
  AlertTriangle,
  TrendingDown,
  TrendingUp,
  Calendar
} from 'lucide-react';
import { toast } from 'sonner@2.0.3';
import { projectId, publicAnonKey } from '../../utils/supabase/info';

interface CommoditiesReportsProps {
  currentUser: any;
  canExport: boolean;
}

export function CommoditiesReports({ currentUser, canExport }: CommoditiesReportsProps) {
  const [commodityType, setCommodityType] = useState('needles');
  const [location, setLocation] = useState('all');
  const [dateRange, setDateRange] = useState('month');
  const [loading, setLoading] = useState(false);
  const [commodityData, setCommodityData] = useState<any>(null);

  const commodities = [
    { id: 'needles', name: 'Needles', unit: 'pieces' },
    { id: 'syringes', name: 'Syringes', unit: 'pieces' },
    { id: 'condoms-male', name: 'Male Condoms', unit: 'pieces' },
    { id: 'condoms-female', name: 'Female Condoms', unit: 'pieces' },
    { id: 'lubricant', name: 'Lubricant', unit: 'packs' },
    { id: 'naloxone', name: 'Naloxone', unit: 'doses' },
    { id: 'methadone', name: 'Methadone', unit: 'ml' },
    { id: 'alcohol-pads', name: 'Alcohol Pads', unit: 'pieces' },
    { id: 'sharps-containers', name: 'Sharps Containers', unit: 'units' },
  ];

  const locations = [
    { value: 'all', label: 'All Locations' },
    { value: 'Mombasa', label: 'Mombasa' },
    { value: 'Lamu', label: 'Lamu' },
    { value: 'Kilifi', label: 'Kilifi' },
  ];

  const dateRanges = [
    { value: 'week', label: 'This Week' },
    { value: 'month', label: 'This Month' },
    { value: 'quarter', label: 'This Quarter' },
    { value: 'year', label: 'This Year' },
  ];

  useEffect(() => {
    loadCommodityData();
  }, [commodityType, location, dateRange]);

  const loadCommodityData = async () => {
    setLoading(true);
    try {
      const params = new URLSearchParams({
        commodity: commodityType,
        location,
        dateRange,
      });

      const response = await fetch(
        `https://${projectId}.supabase.co/functions/v1/make-server-56fd5521/reports/commodities?${params}`,
        { headers: { 'Authorization': `Bearer ${publicAnonKey}` } }
      );

      const data = await response.json();
      if (data.success) {
        setCommodityData(data.data);
      } else {
        toast.error('Failed to load commodity data');
      }
    } catch (error) {
      console.error('Error loading commodity data:', error);
      toast.error('Failed to load commodity data');
    } finally {
      setLoading(false);
    }
  };

  const handleExportPDF = () => {
    if (!canExport) {
      toast.error('You do not have export permissions');
      return;
    }
    
    if (!commodityData) {
      toast.error('No commodity data to export');
      return;
    }

    try {
      const pdfContent = `
        <!DOCTYPE html>
        <html>
        <head>
          <style>
            body { font-family: Arial, sans-serif; padding: 40px; }
            h1 { color: #4f46e5; border-bottom: 2px solid #4f46e5; padding-bottom: 10px; }
            h2 { color: #333; margin-top: 30px; }
            table { width: 100%; border-collapse: collapse; margin-top: 20px; }
            th, td { border: 1px solid #ddd; padding: 12px; text-align: left; }
            th { background-color: #4f46e5; color: white; }
            .metric { display: inline-block; margin: 10px 20px 10px 0; }
            .metric-label { color: #666; font-size: 14px; }
            .metric-value { font-size: 24px; font-weight: bold; color: #333; }
            .alert { background: #fef3c7; padding: 15px; border-left: 4px solid #f59e0b; margin: 20px 0; }
            .logo { font-size: 24px; font-weight: bold; color: #4f46e5; }
          </style>
        </head>
        <body>
          <div class="logo">MEWA M&E System</div>
          <h1>Commodities & Logistics Report</h1>
          <p><strong>Commodity:</strong> ${selectedCommodity?.name}</p>
          <p><strong>Location:</strong> ${location === 'all' ? 'All Locations' : location}</p>
          <p><strong>Period:</strong> ${dateRanges.find(r => r.value === dateRange)?.label}</p>
          <p><strong>Generated:</strong> ${new Date().toLocaleString()}</p>
          <p><strong>Generated by:</strong> ${currentUser.name}</p>

          ${commodityData.lowStock ? '<div class="alert"><strong>⚠️ LOW STOCK ALERT:</strong> Current stock levels are below recommended threshold.</div>' : ''}

          <h2>Stock Overview</h2>
          <div class="metric">
            <div class="metric-label">Current Stock</div>
            <div class="metric-value">${commodityData.currentStock} ${selectedCommodity?.unit}</div>
          </div>
          <div class="metric">
            <div class="metric-label">Total Distributed</div>
            <div class="metric-value">${commodityData.totalDistributed} ${selectedCommodity?.unit}</div>
          </div>
          <div class="metric">
            <div class="metric-label">Stock Received</div>
            <div class="metric-value">${commodityData.totalReceived} ${selectedCommodity?.unit}</div>
          </div>
          <div class="metric">
            <div class="metric-label">Wastage</div>
            <div class="metric-value">${commodityData.wastage} ${selectedCommodity?.unit}</div>
          </div>

          <h2>Forecasting</h2>
          <table>
            <tr><th>Metric</th><th>Value</th></tr>
            <tr><td>Average Daily Consumption</td><td>${commodityData.avgDailyConsumption} ${selectedCommodity?.unit}/day</td></tr>
            <tr><td>Days of Stock Remaining</td><td>${commodityData.daysRemaining} days</td></tr>
            <tr><td>Recommended Reorder Quantity</td><td>${commodityData.recommendedReorder} ${selectedCommodity?.unit}</td></tr>
            <tr><td>Wastage Percentage</td><td>${commodityData.wastagePercentage}%</td></tr>
          </table>

          <h2>Stock Movement History</h2>
          <table>
            <tr>
              <th>Date</th>
              <th>Type</th>
              <th>Quantity</th>
              <th>Location</th>
              <th>User</th>
              <th>Notes</th>
            </tr>
            ${commodityData.movements.map((m: any) => `
              <tr>
                <td>${new Date(m.date).toLocaleDateString()}</td>
                <td>${m.type === 'in' ? 'Stock In' : m.type === 'out' ? 'Distributed' : 'Wastage'}</td>
                <td>${m.quantity} ${selectedCommodity?.unit}</td>
                <td>${m.location}</td>
                <td>${m.user}</td>
                <td>${m.notes || '-'}</td>
              </tr>
            `).join('')}
          </table>

          <p style="margin-top: 40px; color: #666; font-size: 12px;">
            Generated by MEWA M&E System on ${new Date().toLocaleString()}
          </p>
        </body>
        </html>
      `;

      const blob = new Blob([pdfContent], { type: 'text/html' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `commodities_${commodityType}_${new Date().toISOString().split('T')[0]}.html`;
      a.click();
      URL.revokeObjectURL(url);
      
      toast.success('Commodities report exported! Open HTML and print as PDF.');
    } catch (error) {
      console.error('Error exporting PDF:', error);
      toast.error('Failed to export report');
    }
  };

  const handleExportExcel = () => {
    if (!canExport) {
      toast.error('You do not have export permissions');
      return;
    }
    
    if (!commodityData) {
      toast.error('No commodity data to export');
      return;
    }

    try {
      let csvContent = `Commodities & Logistics Report\n`;
      csvContent += `Commodity,${selectedCommodity?.name}\n`;
      csvContent += `Location,${location === 'all' ? 'All Locations' : location}\n`;
      csvContent += `Period,${dateRanges.find(r => r.value === dateRange)?.label}\n`;
      csvContent += `Generated,${new Date().toLocaleString()}\n`;
      csvContent += `Generated by,${currentUser.name}\n\n`;

      csvContent += `Stock Overview\n`;
      csvContent += `Metric,Value\n`;
      csvContent += `Current Stock,${commodityData.currentStock} ${selectedCommodity?.unit}\n`;
      csvContent += `Total Distributed,${commodityData.totalDistributed} ${selectedCommodity?.unit}\n`;
      csvContent += `Stock Received,${commodityData.totalReceived} ${selectedCommodity?.unit}\n`;
      csvContent += `Wastage,${commodityData.wastage} ${selectedCommodity?.unit}\n`;
      csvContent += `Wastage Percentage,${commodityData.wastagePercentage}%\n\n`;

      csvContent += `Forecasting\n`;
      csvContent += `Average Daily Consumption,${commodityData.avgDailyConsumption} ${selectedCommodity?.unit}/day\n`;
      csvContent += `Days of Stock Remaining,${commodityData.daysRemaining} days\n`;
      csvContent += `Recommended Reorder,${commodityData.recommendedReorder} ${selectedCommodity?.unit}\n\n`;

      csvContent += `Stock Movement History\n`;
      csvContent += `Date,Type,Quantity,Location,User,Notes\n`;
      commodityData.movements.forEach((m: any) => {
        const type = m.type === 'in' ? 'Stock In' : m.type === 'out' ? 'Distributed' : 'Wastage';
        csvContent += `${new Date(m.date).toLocaleDateString()},${type},${m.quantity} ${selectedCommodity?.unit},${m.location},${m.user},${m.notes || '-'}\n`;
      });

      const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `commodities_${commodityType}_${new Date().toISOString().split('T')[0]}.csv`;
      a.click();
      URL.revokeObjectURL(url);
      
      toast.success('Commodities report exported to Excel/CSV!');
    } catch (error) {
      console.error('Error exporting Excel:', error);
      toast.error('Failed to export report');
    }
  };

  const selectedCommodity = commodities.find(c => c.id === commodityType);

  return (
    <div className="space-y-6">
      {/* Filters */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Package className="w-5 h-5" />
            Commodities Tracking & Logistics
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <div>
              <Label>Commodity</Label>
              <Select value={commodityType} onValueChange={setCommodityType}>
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {commodities.map(commodity => (
                    <SelectItem key={commodity.id} value={commodity.id}>
                      {commodity.name}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            <div>
              <Label>Location</Label>
              <Select value={location} onValueChange={setLocation}>
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {locations.map(loc => (
                    <SelectItem key={loc.value} value={loc.value}>
                      {loc.label}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            <div>
              <Label>Period</Label>
              <Select value={dateRange} onValueChange={setDateRange}>
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {dateRanges.map(range => (
                    <SelectItem key={range.value} value={range.value}>
                      {range.label}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          </div>

          {canExport && (
            <div className="flex gap-2 mt-4">
              <Button variant="outline" onClick={handleExportPDF}>
                <Download className="w-4 h-4 mr-2" />
                Export PDF
              </Button>
              <Button variant="outline" onClick={handleExportExcel}>
                <FileSpreadsheet className="w-4 h-4 mr-2" />
                Export Excel
              </Button>
            </div>
          )}
        </CardContent>
      </Card>

      {/* Stock Overview */}
      {commodityData && (
        <>
          <Card>
            <CardHeader>
              <CardTitle>
                {selectedCommodity?.name} - Stock Overview
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                <div className="p-4 border rounded-lg">
                  <p className="text-sm text-gray-500 mb-1">Current Stock</p>
                  <p className="text-2xl font-semibold">
                    {commodityData.currentStock || 0}
                    <span className="text-sm text-gray-500 ml-1">{selectedCommodity?.unit}</span>
                  </p>
                  {commodityData.lowStock && (
                    <Badge className="mt-2 bg-amber-100 text-amber-800 text-xs">
                      <AlertTriangle className="w-3 h-3 mr-1" />
                      Low Stock
                    </Badge>
                  )}
                </div>

                <div className="p-4 border rounded-lg">
                  <p className="text-sm text-gray-500 mb-1">Total Distributed</p>
                  <p className="text-2xl font-semibold text-blue-600">
                    {commodityData.totalDistributed || 0}
                    <span className="text-sm text-gray-500 ml-1">{selectedCommodity?.unit}</span>
                  </p>
                  <div className="flex items-center gap-1 mt-2 text-xs text-blue-600">
                    <TrendingUp className="w-3 h-3" />
                    <span>This period</span>
                  </div>
                </div>

                <div className="p-4 border rounded-lg">
                  <p className="text-sm text-gray-500 mb-1">Stock Received</p>
                  <p className="text-2xl font-semibold text-green-600">
                    {commodityData.totalReceived || 0}
                    <span className="text-sm text-gray-500 ml-1">{selectedCommodity?.unit}</span>
                  </p>
                </div>

                <div className="p-4 border rounded-lg">
                  <p className="text-sm text-gray-500 mb-1">Wastage</p>
                  <p className="text-2xl font-semibold text-red-600">
                    {commodityData.wastage || 0}
                    <span className="text-sm text-gray-500 ml-1">{selectedCommodity?.unit}</span>
                  </p>
                  <p className="text-xs text-gray-500 mt-1">
                    {commodityData.wastagePercentage || 0}% of total
                  </p>
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Stock Movement History */}
          <Card>
            <CardHeader>
              <CardTitle>Stock Movement History</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="border rounded-lg overflow-hidden">
                <div className="overflow-x-auto max-h-96">
                  <table className="w-full">
                    <thead className="bg-gray-50 sticky top-0">
                      <tr>
                        <th className="px-4 py-3 text-left text-xs">Date</th>
                        <th className="px-4 py-3 text-left text-xs">Type</th>
                        <th className="px-4 py-3 text-left text-xs">Quantity</th>
                        <th className="px-4 py-3 text-left text-xs">Location</th>
                        <th className="px-4 py-3 text-left text-xs">User</th>
                        <th className="px-4 py-3 text-left text-xs">Notes</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y">
                      {commodityData.movements && commodityData.movements.length > 0 ? (
                        commodityData.movements.map((movement: any, idx: number) => (
                          <tr key={idx} className="hover:bg-gray-50">
                            <td className="px-4 py-3 text-sm">
                              {new Date(movement.date).toLocaleDateString()}
                            </td>
                            <td className="px-4 py-3 text-sm">
                              <Badge 
                                variant="outline"
                                className={
                                  movement.type === 'in' ? 'bg-green-50 text-green-700' :
                                  movement.type === 'out' ? 'bg-blue-50 text-blue-700' :
                                  'bg-red-50 text-red-700'
                                }
                              >
                                {movement.type === 'in' ? 'Stock In' : 
                                 movement.type === 'out' ? 'Distributed' : 
                                 'Wastage'}
                              </Badge>
                            </td>
                            <td className="px-4 py-3 text-sm font-medium">
                              {movement.type === 'in' ? '+' : '-'}{movement.quantity} {selectedCommodity?.unit}
                            </td>
                            <td className="px-4 py-3 text-sm">{movement.location}</td>
                            <td className="px-4 py-3 text-sm">{movement.user}</td>
                            <td className="px-4 py-3 text-sm text-gray-600">{movement.notes || '-'}</td>
                          </tr>
                        ))
                      ) : (
                        <tr>
                          <td colSpan={6} className="px-4 py-8 text-center text-gray-500">
                            No movement records for this period
                          </td>
                        </tr>
                      )}
                    </tbody>
                  </table>
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Forecasting & Alerts */}
          <Card>
            <CardHeader>
              <CardTitle>Forecasting & Alerts</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                {/* Average Daily Consumption */}
                <div className="p-4 border rounded-lg">
                  <div className="flex items-center justify-between mb-2">
                    <p className="font-medium">Average Daily Consumption</p>
                    <Badge variant="outline">
                      {commodityData.avgDailyConsumption || 0} {selectedCommodity?.unit}/day
                    </Badge>
                  </div>
                  <p className="text-sm text-gray-600">
                    Based on last {dateRanges.find(r => r.value === dateRange)?.label.toLowerCase()} usage
                  </p>
                </div>

                {/* Days of Stock Remaining */}
                <div className="p-4 border rounded-lg">
                  <div className="flex items-center justify-between mb-2">
                    <p className="font-medium">Estimated Days of Stock Remaining</p>
                    <Badge className={
                      (commodityData.daysRemaining || 0) < 7 ? 'bg-red-100 text-red-800' :
                      (commodityData.daysRemaining || 0) < 14 ? 'bg-amber-100 text-amber-800' :
                      'bg-green-100 text-green-800'
                    }>
                      {commodityData.daysRemaining || 0} days
                    </Badge>
                  </div>
                  {(commodityData.daysRemaining || 0) < 14 && (
                    <div className="flex items-center gap-2 text-sm text-amber-700 mt-2">
                      <AlertTriangle className="w-4 h-4" />
                      <p>Consider reordering soon</p>
                    </div>
                  )}
                </div>

                {/* Recommended Reorder Quantity */}
                <div className="p-4 border rounded-lg bg-blue-50">
                  <div className="flex items-center justify-between mb-2">
                    <p className="font-medium text-blue-900">Recommended Reorder Quantity</p>
                    <Badge className="bg-blue-600">
                      {commodityData.recommendedReorder || 0} {selectedCommodity?.unit}
                    </Badge>
                  </div>
                  <p className="text-sm text-blue-700">
                    Based on 30-day forecast and safety stock levels
                  </p>
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Location Breakdown (if viewing all locations) */}
          {location === 'all' && commodityData.locationBreakdown && (
            <Card>
              <CardHeader>
                <CardTitle>Stock by Location</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="space-y-3">
                  {Object.entries(commodityData.locationBreakdown).map(([loc, data]: [string, any]) => (
                    <div key={loc} className="p-4 border rounded-lg">
                      <div className="flex items-center justify-between mb-2">
                        <p className="font-medium">{loc}</p>
                        <Badge variant="outline">
                          {data.stock} {selectedCommodity?.unit}
                        </Badge>
                      </div>
                      <div className="flex gap-4 text-sm text-gray-600">
                        <span>Distributed: {data.distributed}</span>
                        <span>Received: {data.received}</span>
                        {data.lowStock && (
                          <Badge className="bg-amber-100 text-amber-800 text-xs">
                            Low Stock
                          </Badge>
                        )}
                      </div>
                    </div>
                  ))}
                </div>
              </CardContent>
            </Card>
          )}
        </>
      )}

      {/* Loading/Empty State */}
      {!commodityData && !loading && (
        <Card>
          <CardContent className="py-12 text-center text-gray-500">
            <Package className="w-12 h-12 mx-auto mb-4 text-gray-300" />
            <p>Loading commodity data...</p>
          </CardContent>
        </Card>
      )}
    </div>
  );
}