/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "kdbufmnjakebcgzwyutm"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtkYnVmbW5qYWtlYmNnend5dXRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI1MTk4NzEsImV4cCI6MjA3ODA5NTg3MX0.yXiw8xoWsp4Dv-iqujDcoZ6VGllChoZ9MvCfAr6-vow"